name: DevSecOps Security Scan
on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hard Security Gate
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          # We force it to look for BOTH vulnerabilities and secrets
          scanners: 'vuln,secret' 
          format: 'table'
          # This MUST exit with 1 if it finds anything
          exit-code: '1'
          # Lowered severity to 'MEDIUM' to ensure it catches the old 'requests'
          severity: 'CRITICAL,HIGH,MEDIUM'